
public enum Class {
	NONE, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, WARRIOR_PROTECTION, WARRIOR_FURY, WARRIOR_ARMS, DRUID_GUARDIAN, DRUID_RESTORATION, DRUID_BALANCE, DRUID_FERAL, PALADIN_PROTECTION, PALADIN_HOLY, PALADIN_RETRIBUTION, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST, DEATHKNIGHT_UNHOLY, PRIEST_HOLY, PRIEST_DISCIPLINE, PRIEST_SHADOW, HUNTER_MARKMANSHIP, HUNTER_BEASTMASTERY, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, ROGUE_SUBTLETY, ROGUE_OUTLAW, ROGUE_ASSASINATION, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DESTRUCTION, WARLOCK_DEMONOLOGY;
}
